/*
 * Videogame API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// VideogameApiRouter defines the required methods for binding the api requests to a responses for the VideogameApi
// The VideogameApiRouter implementation should parse necessary information from the http request, 
// pass the data to a VideogameApiServicer to perform the required actions, then write the service results to the http response.
type VideogameApiRouter interface { 
	CreateVideogame(http.ResponseWriter, *http.Request)
	SearchVideogames(http.ResponseWriter, *http.Request)
}


// VideogameApiServicer defines the api actions for the VideogameApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type VideogameApiServicer interface { 
	CreateVideogame(Videogame) (interface{}, error)
	SearchVideogames(SearchRequest) (interface{}, error)
}
