/*
 * Videogame API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// VideogameApiService is a service that implents the logic for the VideogameApiServicer
// This service should implement the business logic for every endpoint for the VideogameApi API. 
// Include any external packages or services that will be required by this service.
type VideogameApiService struct {
}

// NewVideogameApiService creates a default api service
func NewVideogameApiService() VideogameApiServicer {
	return &VideogameApiService{}
}

// CreateVideogame - Create a Videogame
func (s *VideogameApiService) CreateVideogame(videogame Videogame) (interface{}, error) {
	// TODO - update CreateVideogame with the required logic for this service method.
	// Add api_videogame_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'CreateVideogame' not implemented")
}

// SearchVideogames - Search Videogames
func (s *VideogameApiService) SearchVideogames(searchRequest SearchRequest) (interface{}, error) {
	// TODO - update SearchVideogames with the required logic for this service method.
	// Add api_videogame_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'SearchVideogames' not implemented")
}
