/*
 * Videogame API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Videogame struct {

	Id string `json:"id,omitempty"`

	Title string `json:"title"`

	ReleaseDate string `json:"releaseDate"`

	Publisher string `json:"publisher"`
}
