/*
 * Videogame API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SearchRequest struct {

	Offset int32 `json:"offset,omitempty"`

	Limit int32 `json:"limit,omitempty"`

	SortBy string `json:"sortBy,omitempty"`

	SortType string `json:"sortType,omitempty"`

	Title string `json:"title,omitempty"`
}
